services:
  q_tracker:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"
    # volumes:
    #   - "./data:/app/data"
    environment:
      - PUSH_PRIVATE_KEY=
      - PUSH_PUBLIC_KEY=
      - SUBSCRIBER=
      - ADMIN_CONSOLE_PSW= #admin console password here
    container_name: q_tracker
    restart: unless-stopped
