services:
  kfs_qtracker:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - "./data:/app/data"
    ports:
      - "8080:8080"
    environment:
      - PUSH_PRIVATE_KEY=your_super_secret_private_key_here
      - PUSH_PUBLIC_KEY=your_public_key_here
    container_name: kfs_qtracker
    restart: unless-stopped
